# Generated by Django 4.2.3 on 2025-01-11 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fapp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="flight",
            name="dateOfDeparture",
            field=models.CharField(max_length=30),
        ),
    ]
